### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by mlowens** [rockfordweb/rockfordweb.github.com#1]
![screen shot 2015-01-19 at 2 49 06 pm](https://cloud.githubusercontent.com/assets/974050/5807579/5741d990-9fea-11e4-95a0-dfaee6efa72c.png)

Site Not Found

Well, this is awkward. The site you're looking for is not here.

Is this your site? Get more info or contact support.

**Comment by jacobroufa** [comment]
Updated DNS A record for root and the www. subdomain. Hopefully it will start serving correctly now. Re-open if this is still happening.

**Comment by jonweber** [comment]
It's still only working -without- the "www" prefix.

**Comment by jacobroufa** [comment]
This appears to be fixed. "www" redirects to rockdevs.com.
